### ISSUE TITLE
error when gluestick

### ISSUE THREAD

**Issue by TwiceMao** [Vincentqyw/image-matching-webui#13]
```
[2023/09/04 05:01:50 hloc.matchers.gluestick INFO] Loading GlueStick model...
Traceback (most recent call last):
  File "/home/maomao/anaconda3/envs/imw/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/maomao/anaconda3/envs/imw/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/maomao/anaconda3/envs/imw/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/maomao/anaconda3/envs/imw/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/maomao/anaconda3/envs/imw/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/maomao/anaconda3/envs/imw/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/maomao/anaconda3/envs/imw/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/maomao/Codes/image-matching-webui/common/utils.py", line 330, in run_matching
    matcher = get_model(match_conf)
  File "/home/maomao/Codes/image-matching-webui/common/utils.py", line 19, in get_model
    model = Model(match_conf["model"]).eval().to(device)
  File "/home/maomao/Codes/image-matching-webui/hloc/utils/base_model.py", line 17, in __init__
    self._init(conf)
  File "/home/maomao/Codes/image-matching-webui/hloc/matchers/gluestick.py", line 83, in _init
    self.net = TwoViewPipeline(gluestick_conf)
  File "/home/maomao/Codes/image-matching-webui/hloc/matchers/../../third_party/GlueStick/gluestick/models/base_model.py", line 80, in __init__
    self._init(conf)
  File "/home/maomao/Codes/image-matching-webui/hloc/matchers/../../third_party/GlueStick/gluestick/models/two_view_pipeline.py", line 106, in _init
    self.matcher = get_model(conf.matcher.name)(conf.matcher)
  File "/home/maomao/Codes/image-matching-webui/hloc/matchers/../../third_party/GlueStick/gluestick/models/base_model.py", line 80, in __init__
    self._init(conf)
  File "/home/maomao/Codes/image-matching-webui/hloc/matchers/../../third_party/GlueStick/gluestick/models/gluestick.py", line 90, in _init
    state_dict = torch.load(conf.weights, map_location='cpu')
  File "/home/maomao/anaconda3/envs/imw/lib/python3.10/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/maomao/anaconda3/envs/imw/lib/python3.10/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```

**Comment by Vincentqyw** [comment]
Please download the [weights ](https://github.com/cvg/GlueStick/releases/download/v0.1_arxiv/checkpoint_GlueStick_MD.tar)of the gluestick model and put it to `third_party/GlueStick/resources/weights/`
