### ISSUE TITLE
[datasets/wxbs_benchmark/.WxBS/] Error

### ISSUE THREAD

**Issue by Ever-Bright-V** [Vincentqyw/image-matching-webui#37]
python ./app.py 
Traceback (most recent call last):
  File "./app.py", line 26, in <module>
    ImageMatchingApp(
  File "/home/everbright/CodesWorld/Codes/image-matching-webui/common/app_class.py", line 41, in __init__
    self.init_interface()
  File "/home/everbright/CodesWorld/Codes/image-matching-webui/common/app_class.py", line 216, in init_interface
    examples=gen_examples(),
  File "/home/everbright/CodesWorld/Codes/image-matching-webui/common/utils.py", line 275, in gen_examples
    pairs += gen_image_pairs_wxbs()
  File "/home/everbright/CodesWorld/Codes/image-matching-webui/common/utils.py", line 258, in gen_image_pairs_wxbs
    for catg in os.listdir(wxbs_path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/everbright/CodesWorld/Codes/image-matching-webui/datasets/wxbs_benchmark/.WxBS/v1.1'

**Comment by Vincentqyw** [comment]
This issue has been resolved. Please note that I maintain two sets of codebases, one on Hugging Face and one on GitHub. The code on [Hugging Face](https://huggingface.co/spaces/Realcat/image-matching-webui/tree/main) is kept up to date, while the one on GitHub may lag slightly behind but will be kept as consistent as possible. Additionally, it's important to note that on GitHub, to ensure small repository sizes, a lot of submodules are used, which is not the case on Hugging Face. If you want to quickly try out the functionality of this repository, I recommend using [Docker](https://hub.docker.com/r/vincentqin/image-matching-webui) or the code on Hugging Face for now. In the future, I will consider adding CI to prevent similar issues from occurring.
