### ISSUE TITLE
KeyError: 'force_resize'

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Vincentqyw/image-matching-webui#54]
## 🐛 Bug Report

Full trace:

```
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.28.3, however version 4.29.0 is available, please upgrade.
--------
Downloading: "https://github.com/cvg/LightGlue/releases/download/v0.1_arxiv/disk_lightglue.pth" to /home/username/.cache/torch/hub/checkpoints/disk_lightglue_v0-1_arxiv.pth
100%|███████████████████████████████████████████████████████████| 45.4M/45.4M [00:00<00:00, 69.2MB/s]
[2024/08/19 11:02:38 hloc INFO] Load lightglue model done.
[2024/08/19 11:02:39 hloc INFO] Loading model using: 1.722s
Downloading: "https://raw.githubusercontent.com/cvlab-epfl/disk/master/depth-save.pth" to /home/username/.cache/torch/hub/checkpoints/depth-save.pth
100%|███████████████████████████████████████████████████████████| 4.17M/4.17M [00:00<00:00, 42.8MB/s]
[2024/08/19 11:02:39 hloc INFO] Load DISK model done.
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/imw/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/home/username/anaconda3/envs/imw/lib/python3.10/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/username/anaconda3/envs/imw/lib/python3.10/site-packages/gradio/blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "/home/username/anaconda3/envs/imw/lib/python3.10/site-packages/gradio/blocks.py", line 1433, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/username/anaconda3/envs/imw/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/username/anaconda3/envs/imw/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/username/anaconda3/envs/imw/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/username/anaconda3/envs/imw/lib/python3.10/site-packages/gradio/utils.py", line 788, in wrapper
    response = f(*args, **kwargs)
  File "/home/username/image-matching-webui/ui/utils.py", line 944, in run_matching
    if not extract_conf["preprocessing"]["force_resize"]:
KeyError: 'force_resize'


```
## 🔬 How To Reproduce

Local installation. Simply running the .py file, uploading two images and pressing run reproduces this error. Default settings.

### Environment

- OS: Ubuntu 22.04
- Python version: Python 3.10.10

**Comment by eyildiz-ugoe** [comment]
OK, this seems to fix it in file "..image-matching-webui/ui/utils.py", line 944, in run_matching:

```
if not extract_conf["preprocessing"].get("force_resize", False):
    extract_conf["preprocessing"]["force_resize"] = force_resize
else:
    logger.info("preprocessing is already resized")
```

**Comment by eyildiz-ugoe** [comment]
Not sure if you integrated this one @Vincentqyw
