### ISSUE TITLE
Models did't download into the paths wanted 

### ISSUE THREAD

**Issue by ahmedmustafa2002** [Vincentqyw/image-matching-webui#98]
To create a public link, set `share=True` in `launch()`.
[2024/11/20 11:49:47 hloc INFO] Run Match first before Rerun RANSAC
Traceback (most recent call last):
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/gradio/blocks.py", line 2025, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1781, in postprocess_data
    self.validate_outputs(block_fn, predictions)  # type: ignore
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1736, in validate_outputs
    raise ValueError(
ValueError: A  function (run_ransac) didn't return enough output values (needed: 4, returned: 2).
    Output components:
        [image, json, image, file]
    Output values returned:
        [None, None]
Traceback (most recent call last):
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/gradio/blocks.py", line 2015, in process_api
    result = await self.call_function(
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1562, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/ahmedmustafa/.local/lib/python3.10/site-packages/gradio/utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "/home/ahmedmustafa/Downloads/image-matching-webui/ui/utils.py", line 910, in run_matching
    matcher = get_model(match_conf)
  File "/home/ahmedmustafa/Downloads/image-matching-webui/ui/utils.py", line 176, in get_model
    Model = dynamic_load(matchers, match_conf["model"]["name"])
  File "/home/ahmedmustafa/Downloads/image-matching-webui/hloc/utils/base_model.py", line 47, in dynamic_load
    module = __import__(module_path, fromlist=[""])
  File "/home/ahmedmustafa/Downloads/image-matching-webui/hloc/matchers/lightglue.py", line 9, in <module>
    from lightglue import LightGlue as LG
ModuleNotFoundError: No module named 'lightglue'

**Comment by Vincentqyw** [comment]
Did you download submodule? If not, please re-download using the following cmd:
``` bash
git clone --recursive https://github.com/Vincentqyw/image-matching-webui.git
```
If remote submodule repositories are updated, don't forget to pull submodules with:
``` bash
git submodule init
git submodule update --remote 
```
